version: '3'
services:
  db:
    image: mysql:8.0.31
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: youssef
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: miniprojet

    ports:
      - "3307:3306"
    networks:
      - backend-network

  backend:
    build: ./back
    command: sh -c "ls && ./sql/wait.sh && python manage.py migrate  && mysql -h db -u youssef -proot miniprojet < /app/sql/init.sql && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./back:/app
    ports:
      - "8000:8000"
    depends_on:
      - db   
    networks:
      - backend-network
      - frontend-network


  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - frontend-network
      - backend-network
networks:
  frontend-network:
  backend-network: